### ISSUE TITLE
Putting the Token into the console

### ISSUE THREAD

**Issue by wsmigielski** [wsmigielski/DiscordSpotifyBot#4]
The console asking for your token instead of you having to edit config.json

**Comment by tilda** [comment]
Maybe you could check if the config has the token inside, if not then ask for it

**Comment by wsmigielski** [comment]
Yeah I was thinking something along those lines but I am not familiar with promises and such in nodejs.

**Comment by tilda** [comment]
I'd think something like this:

```js
var conf = JSON.parse(require('fs').readFileSync('config.json', 'utf8'))

if (conf.token=="")
    // ask for token
else
    // run bot from config
```
