### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by stuntguy3000** [wsmigielski/DiscordSpotifyBot#8]
Hi @wsmigielski 

Unfortunately this seems to no longer be working. (The discord status bit)

Can you fix it?

Cheers

**Comment by wsmigielski** [comment]
Hey, I'm sorry but this is super outdated and I don't have the time to fix it. However [this](https://github.com/WalshyDev/Discord-Spotify-RPC), works the same and is constantly updated. It is also more visually appealing.

**Comment by stuntguy3000** [comment]
No worries.

Cheers!
